BEGIN;

CREATE TABLE IF NOT EXISTS customers (
  id text PRIMARY KEY,
  name text NOT NULL CHECK (length(btrim(name)) > 0),
  phone_e164 text NOT NULL CHECK (length(btrim(phone_e164)) > 0),
  email text NOT NULL UNIQUE CHECK (length(btrim(email)) > 0),
  shopfront_customer_id text,
  marketing_email_consent boolean NOT NULL DEFAULT false,
  marketing_sms_consent boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Runtime bootstrap versions of these tables intentionally start smaller. Add
-- every integration field before any index references it so this migration can
-- run both first and after the application initializer.
ALTER TABLE customers ADD COLUMN IF NOT EXISTS shopfront_customer_id text;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS marketing_email_consent boolean NOT NULL DEFAULT false;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS marketing_sms_consent boolean NOT NULL DEFAULT false;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'customers_name_check' AND conrelid = 'customers'::regclass
  ) THEN
    ALTER TABLE customers ADD CONSTRAINT customers_name_check CHECK (length(btrim(name)) > 0);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'customers_phone_e164_check' AND conrelid = 'customers'::regclass
  ) THEN
    ALTER TABLE customers ADD CONSTRAINT customers_phone_e164_check CHECK (length(btrim(phone_e164)) > 0);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'customers_email_check' AND conrelid = 'customers'::regclass
  ) THEN
    ALTER TABLE customers ADD CONSTRAINT customers_email_check CHECK (length(btrim(email)) > 0);
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS customers_email_lower_idx ON customers (lower(email));
CREATE UNIQUE INDEX IF NOT EXISTS customers_shopfront_customer_idx
  ON customers (shopfront_customer_id)
  WHERE shopfront_customer_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS customer_addresses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id text NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  label text NOT NULL DEFAULT 'Delivery',
  formatted_address text NOT NULL CHECK (length(btrim(formatted_address)) > 0),
  google_place_id text,
  latitude numeric(9, 6),
  longitude numeric(9, 6),
  is_default boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE customer_addresses ADD COLUMN IF NOT EXISTS label text NOT NULL DEFAULT 'Delivery';
ALTER TABLE customer_addresses ADD COLUMN IF NOT EXISTS google_place_id text;
ALTER TABLE customer_addresses ADD COLUMN IF NOT EXISTS latitude numeric(9, 6);
ALTER TABLE customer_addresses ADD COLUMN IF NOT EXISTS longitude numeric(9, 6);
ALTER TABLE customer_addresses ADD COLUMN IF NOT EXISTS is_default boolean NOT NULL DEFAULT false;
ALTER TABLE customer_addresses ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE customer_addresses ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'customer_addresses_formatted_address_check'
      AND conrelid = 'customer_addresses'::regclass
  ) THEN
    ALTER TABLE customer_addresses ADD CONSTRAINT customer_addresses_formatted_address_check
      CHECK (length(btrim(formatted_address)) > 0);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS customer_addresses_customer_idx ON customer_addresses (customer_id);
CREATE UNIQUE INDEX IF NOT EXISTS customer_addresses_customer_address_idx
  ON customer_addresses (customer_id, formatted_address);
CREATE UNIQUE INDEX IF NOT EXISTS customer_addresses_one_default_idx
  ON customer_addresses (customer_id)
  WHERE is_default;

CREATE TABLE IF NOT EXISTS store_products (
  id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 10000) PRIMARY KEY,
  source text NOT NULL DEFAULT 'manual' CHECK (source IN ('manual', 'shopfront')),
  source_product_id text,
  shopfront_product_id text,
  shopfront_variant_id text,
  sku text,
  name text NOT NULL CHECK (length(btrim(name)) > 0),
  slug text NOT NULL,
  alcohol_type text NOT NULL,
  description text NOT NULL DEFAULT '',
  image_url text,
  volume_label text,
  price_cents integer CHECK (price_cents IS NULL OR price_cents >= 0),
  compare_at_price_cents integer CHECK (compare_at_price_cents IS NULL OR compare_at_price_cents >= 0),
  inventory_quantity integer CHECK (inventory_quantity IS NULL OR inventory_quantity >= 0),
  currency char(3) NOT NULL DEFAULT 'AUD',
  is_active boolean NOT NULL DEFAULT true,
  is_placeholder boolean NOT NULL DEFAULT false,
  is_new boolean NOT NULL DEFAULT false,
  is_on_sale boolean NOT NULL DEFAULT false,
  is_member_offer boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT store_products_placeholder_price_check
    CHECK (is_placeholder OR price_cents IS NOT NULL)
);

ALTER TABLE store_products
  ADD COLUMN IF NOT EXISTS is_member_offer boolean NOT NULL DEFAULT false;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'store_products_source_check' AND conrelid = 'store_products'::regclass
  ) THEN
    ALTER TABLE store_products ADD CONSTRAINT store_products_source_check
      CHECK (source IN ('manual', 'shopfront'));
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'store_products_price_cents_check' AND conrelid = 'store_products'::regclass
  ) THEN
    ALTER TABLE store_products ADD CONSTRAINT store_products_price_cents_check
      CHECK (price_cents IS NULL OR price_cents >= 0);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'store_products_compare_at_price_cents_check' AND conrelid = 'store_products'::regclass
  ) THEN
    ALTER TABLE store_products ADD CONSTRAINT store_products_compare_at_price_cents_check
      CHECK (compare_at_price_cents IS NULL OR compare_at_price_cents >= 0);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'store_products_inventory_quantity_check' AND conrelid = 'store_products'::regclass
  ) THEN
    ALTER TABLE store_products ADD CONSTRAINT store_products_inventory_quantity_check
      CHECK (inventory_quantity IS NULL OR inventory_quantity >= 0);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'store_products_placeholder_price_check' AND conrelid = 'store_products'::regclass
  ) THEN
    ALTER TABLE store_products ADD CONSTRAINT store_products_placeholder_price_check
      CHECK (is_placeholder OR price_cents IS NOT NULL);
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS store_products_slug_idx ON store_products (slug);
CREATE UNIQUE INDEX IF NOT EXISTS store_products_sku_idx
  ON store_products (sku)
  WHERE sku IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS store_products_source_product_idx
  ON store_products (source, source_product_id)
  WHERE source_product_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS store_products_shopfront_product_idx
  ON store_products (shopfront_product_id)
  WHERE shopfront_product_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS store_products_catalogue_idx
  ON store_products (is_active, alcohol_type, name);

CREATE TABLE IF NOT EXISTS daily_offers (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id integer REFERENCES store_products(id) ON DELETE SET NULL,
  shopfront_promotion_id text,
  title text NOT NULL CHECK (length(btrim(title)) > 0),
  description text NOT NULL DEFAULT '',
  eyebrow text NOT NULL DEFAULT 'DAILY OFFER',
  image_url text,
  link_url text,
  badge text,
  starts_at timestamptz NOT NULL,
  ends_at timestamptz NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT daily_offers_date_order_check CHECK (ends_at > starts_at)
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'daily_offers_date_order_check' AND conrelid = 'daily_offers'::regclass
  ) THEN
    ALTER TABLE daily_offers ADD CONSTRAINT daily_offers_date_order_check CHECK (ends_at > starts_at);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS daily_offers_active_window_idx
  ON daily_offers (is_active, starts_at, ends_at, sort_order);
CREATE UNIQUE INDEX IF NOT EXISTS daily_offers_shopfront_promotion_idx
  ON daily_offers (shopfront_promotion_id)
  WHERE shopfront_promotion_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS shopfront_sync_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shopfront_event_id text NOT NULL UNIQUE,
  event_type text NOT NULL,
  entity_type text,
  entity_id text,
  payload jsonb NOT NULL,
  processing_status text NOT NULL DEFAULT 'pending'
    CHECK (processing_status IN ('pending', 'processed', 'failed', 'ignored')),
  attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  last_error text,
  occurred_at timestamptz,
  received_at timestamptz NOT NULL DEFAULT now(),
  processed_at timestamptz
);

CREATE INDEX IF NOT EXISTS shopfront_sync_events_processing_idx
  ON shopfront_sync_events (processing_status, received_at);
CREATE INDEX IF NOT EXISTS shopfront_sync_events_entity_idx
  ON shopfront_sync_events (entity_type, entity_id);

-- Keep this migration safe on an empty database as well as the current app.
CREATE TABLE IF NOT EXISTS customer_accounts (
  id text PRIMARY KEY,
  email text NOT NULL UNIQUE,
  display_name text NOT NULL,
  credit_balance_cents integer NOT NULL DEFAULT 0 CHECK (credit_balance_cents >= 0),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS orders (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  checkout_token text,
  checkout_fingerprint text,
  order_number text NOT NULL UNIQUE,
  account_id text REFERENCES customer_accounts(id),
  customer_id text REFERENCES customers(id),
  customer_name text NOT NULL,
  customer_email text NOT NULL,
  customer_phone text NOT NULL DEFAULT '',
  receipt_preference text NOT NULL DEFAULT 'email',
  delivery_address text NOT NULL,
  delivery_instructions text NOT NULL DEFAULT '',
  delivery_slot text NOT NULL,
  delivery_method text NOT NULL DEFAULT 'express',
  delivery_date date,
  destination_place_id text,
  distance_meters integer NOT NULL DEFAULT 0,
  duration_seconds integer NOT NULL DEFAULT 0,
  delivery_rate_cents_per_km integer NOT NULL DEFAULT 0,
  subtotal_cents integer NOT NULL CHECK (subtotal_cents >= 0),
  delivery_fee_cents integer NOT NULL CHECK (delivery_fee_cents >= 0),
  maintenance_fee_cents integer NOT NULL DEFAULT 99 CHECK (maintenance_fee_cents >= 0),
  gst_included_cents integer NOT NULL DEFAULT 0 CHECK (gst_included_cents >= 0),
  total_cents integer NOT NULL CHECK (total_cents >= 0),
  payment_method text NOT NULL DEFAULT 'account_credit',
  stripe_session_id text,
  stripe_payment_intent_id text,
  shopfront_sale_id text,
  shopfront_fulfilment_id text,
  status text NOT NULL DEFAULT 'confirmed',
  inventory_reservation_state text NOT NULL DEFAULT 'not_applicable',
  inventory_reserved_at timestamptz,
  inventory_released_at timestamptz,
  paid_at timestamptz,
  notifications_sent_at timestamptz,
  notifications_claimed_at timestamptz,
  notifications_claim_token text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT orders_delivery_method_check
    CHECK (delivery_method IN ('express', 'normal')),
  CONSTRAINT orders_distance_nonnegative_check CHECK (distance_meters >= 0),
  CONSTRAINT orders_duration_nonnegative_check CHECK (duration_seconds >= 0)
);

ALTER TABLE orders ADD COLUMN IF NOT EXISTS checkout_token text;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS checkout_fingerprint text;
ALTER TABLE orders ALTER COLUMN account_id DROP NOT NULL;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS customer_id text REFERENCES customers(id);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS customer_phone text NOT NULL DEFAULT '';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS receipt_preference text NOT NULL DEFAULT 'email';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_instructions text NOT NULL DEFAULT '';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_method text NOT NULL DEFAULT 'express';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_date date;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS destination_place_id text;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS distance_meters integer NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS duration_seconds integer NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_rate_cents_per_km integer NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS maintenance_fee_cents integer NOT NULL DEFAULT 99;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS gst_included_cents integer NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_method text NOT NULL DEFAULT 'account_credit';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS stripe_session_id text;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS stripe_payment_intent_id text;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS shopfront_sale_id text;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS shopfront_fulfilment_id text;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS inventory_reservation_state text NOT NULL DEFAULT 'not_applicable';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS inventory_reserved_at timestamptz;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS inventory_released_at timestamptz;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS paid_at timestamptz;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS notifications_sent_at timestamptz;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS notifications_claimed_at timestamptz;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS notifications_claim_token text;
ALTER TABLE orders ALTER COLUMN maintenance_fee_cents SET DEFAULT 99;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'orders_delivery_method_check' AND conrelid = 'orders'::regclass
  ) THEN
    ALTER TABLE orders ADD CONSTRAINT orders_delivery_method_check
      CHECK (delivery_method IN ('express', 'normal'));
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'orders_distance_nonnegative_check' AND conrelid = 'orders'::regclass
  ) THEN
    ALTER TABLE orders ADD CONSTRAINT orders_distance_nonnegative_check
      CHECK (distance_meters IS NULL OR distance_meters >= 0);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'orders_duration_nonnegative_check' AND conrelid = 'orders'::regclass
  ) THEN
    ALTER TABLE orders ADD CONSTRAINT orders_duration_nonnegative_check
      CHECK (duration_seconds IS NULL OR duration_seconds >= 0);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'orders_checkout_fingerprint_check' AND conrelid = 'orders'::regclass
  ) THEN
    ALTER TABLE orders ADD CONSTRAINT orders_checkout_fingerprint_check
      CHECK (checkout_fingerprint IS NULL OR checkout_fingerprint ~ '^[0-9a-f]{64}$');
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'orders_inventory_reservation_state_check' AND conrelid = 'orders'::regclass
  ) THEN
    ALTER TABLE orders ADD CONSTRAINT orders_inventory_reservation_state_check
      CHECK (inventory_reservation_state IN ('not_applicable', 'reserved', 'released', 'consumed'));
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'orders_inventory_reservation_fingerprint_check' AND conrelid = 'orders'::regclass
  ) THEN
    ALTER TABLE orders ADD CONSTRAINT orders_inventory_reservation_fingerprint_check
      CHECK (
        inventory_reservation_state = 'not_applicable'
        OR (checkout_fingerprint IS NOT NULL AND inventory_reserved_at IS NOT NULL)
      );
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS orders_checkout_token_idx
  ON orders (checkout_token);
CREATE UNIQUE INDEX IF NOT EXISTS orders_stripe_session_idx
  ON orders (stripe_session_id)
  WHERE stripe_session_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS orders_customer_idx ON orders (customer_id);
CREATE INDEX IF NOT EXISTS orders_auspost_report_idx
  ON orders (delivery_date, status)
  WHERE delivery_method = 'normal';
CREATE UNIQUE INDEX IF NOT EXISTS orders_shopfront_sale_idx
  ON orders (shopfront_sale_id)
  WHERE shopfront_sale_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS orders_notifications_pending_idx
  ON orders (notifications_claimed_at)
  WHERE status = 'paid' AND notifications_sent_at IS NULL;
CREATE INDEX IF NOT EXISTS orders_inventory_reservation_idx
  ON orders (status, inventory_reservation_state, created_at);

CREATE TABLE IF NOT EXISTS order_items (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  order_number text NOT NULL REFERENCES orders(order_number) ON DELETE CASCADE,
  product_id integer NOT NULL,
  product_name text NOT NULL,
  unit_price_cents integer NOT NULL,
  quantity integer NOT NULL
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'order_items_unit_price_nonnegative_check' AND conrelid = 'order_items'::regclass
  ) THEN
    ALTER TABLE order_items ADD CONSTRAINT order_items_unit_price_nonnegative_check
      CHECK (unit_price_cents >= 0);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'order_items_quantity_check' AND conrelid = 'order_items'::regclass
  ) THEN
    ALTER TABLE order_items ADD CONSTRAINT order_items_quantity_check
      CHECK (quantity > 0 AND quantity <= 24);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS order_items_order_idx ON order_items (order_number);
CREATE UNIQUE INDEX IF NOT EXISTS order_items_order_product_idx
  ON order_items (order_number, product_id);

CREATE TABLE IF NOT EXISTS account_transactions (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  account_id text NOT NULL REFERENCES customer_accounts(id),
  order_number text NOT NULL REFERENCES orders(order_number),
  amount_cents integer NOT NULL,
  transaction_type text NOT NULL DEFAULT 'order_charge',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS account_transactions_order_idx
  ON account_transactions (order_number);
CREATE INDEX IF NOT EXISTS account_transactions_account_idx
  ON account_transactions (account_id, created_at DESC);

COMMENT ON COLUMN orders.maintenance_fee_cents IS
  'Technology and maintenance fee. New web orders are expected to write 99 cents explicitly.';
COMMENT ON COLUMN orders.gst_included_cents IS
  'GST component already included in the customer-facing total; it is not added on top.';

CREATE TABLE IF NOT EXISTS daily_report_runs (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  report_type text NOT NULL DEFAULT 'auspost_next_business_day',
  delivery_date date NOT NULL,
  recipient_email text NOT NULL,
  order_count integer NOT NULL DEFAULT 0 CHECK (order_count >= 0),
  sent_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  UNIQUE (report_type, delivery_date, recipient_email)
);

ALTER TABLE daily_report_runs ADD COLUMN IF NOT EXISTS completed_at timestamptz;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'daily_report_runs_order_count_check'
      AND conrelid = 'daily_report_runs'::regclass
  ) THEN
    ALTER TABLE daily_report_runs ADD CONSTRAINT daily_report_runs_order_count_check
      CHECK (order_count >= 0);
  END IF;
END $$;

COMMIT;
